### ISSUE TITLE
PhpReport login page should redirect if already logged in

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#494] opened 2021-03-16 10:32 UTC
The login page is setup to redirect you to tasks.php (or any page that was set as the `login_success_url` GET variable) after a successful login.

We should also perform the same relocation if a user enters this page (e.g. by typing its URL) when it's already logged in. The index page redirects to login.php, which makes this issue more visible.

**Comment by AtmegaBuzz** [comment] 2023-07-05 20:35
Hey @jaragunde, I'm new to this org and want to contribute to it. Can you assign this to me

**Comment by anarute** [comment] 2023-07-05 21:14
@AtmegaBuzz since this issue is a bit old, I'm trying to reproduce it and it doesn't seem to be an issue anymore. @jaragunde is on leave so he may take a while to reply, I would wait for him to avoid spending time on something that is not a real issue anymore, but thanks for volunteering!

**Comment by AtmegaBuzz** [comment] 2023-07-05 21:17
@anarute I ran the main branch in my machine and it seem to be happening on my end. after logging in if i go back to base url localhost:8000 it redirects me to login.php not to tasks.php

**Comment by AtmegaBuzz** [comment] 2023-07-06 15:06
Sure I would like to work on it you can assign it to me, Thanks @dmtrek14

**Comment by anarute** [comment] 2023-07-07 14:25
@AtmegaBuzz You're right this behavior was happening indeed and I couldn't see it because we use a different authentication method. Thank you for the fix!

**Closed by anarute** 2023-07-07 14:25 UTC
Labels: type: enhancement, component: frontend, good first issue, hacktoberfest
