### ISSUE TITLE
Cloned tasks can contain URL-encoded text

### ISSUE THREAD

**Issue by mrobinson** [Igalia/phpreport#344] opened 2017-03-22 13:55 UTC
If you create a task with the text ```"text"``` (that includes the double quotes) in the task story of task description field, the cloned version of that task has the text ```&quot;text&quot;.```

**Comment by jaragunde** [comment] 2017-03-22 16:02
Sorry, I don't understand what's the problem here.

**Comment by mrobinson** [comment] 2017-03-22 16:41
Ack. Github decoded my URL-encoded text. Take a look at the first comment again. The weird thing is that I don't see this issue any longer on the live site.

**Comment by jaragunde** [comment] 2017-04-21 16:19
I've seen this bug happening, I had written `it's` in some task description and it was cloned as `it&apos;s`. To reproduce the bug, I think there must be some timeout involved. I left the page open for some hours and it happened when I came back. Then, I reloaded and tried again and things worked normally.

**Comment by jaragunde** [comment] 2018-06-25 15:53
This is actually a duplicate of #85, which has specific steps to reproduce. Closing this bug.

**Closed by jaragunde** 2018-06-25 15:53 UTC
Labels: bug, component: frontend, resolution: duplicate, use case: tasks
